#### 1、现在有数组a和数组b，将a数组中大于对应b数组的元素赋值为100，其他不变。

In [22]:
import numpy as np

In [23]:
a = np.array([3,7,2,1,9])
b = np.array([4,5,1,3,7])

In [24]:
c = np.where(a>b,100,a)
c

array([  3, 100, 100,   1, 100])

#### 2、生成一组3*6的标准正态分布随机数组
##### ① 利用数组基本统计方法，找出其中的最大值和最小值；
##### ② 利用排序和数组索引，找出其中的最大值和最小值

In [11]:
arr=np.random.normal(size=(3,6))
arr

array([[-1.47289261,  0.25021438,  2.0603444 ,  1.60772698, -0.77818867,
         0.76027132],
       [-0.14532864, -0.7920735 , -0.37514185,  0.72588025,  0.8916625 ,
        -1.25463262],
       [-1.38176421, -1.0957435 ,  0.63971315, -1.41551597, -2.24116762,
        -0.11972352]])

In [12]:
arr.max()

2.0603443986202983

In [31]:
np.max(arr)

2.0603443986202983

In [13]:
arr.min()

-2.2411676156967255

In [32]:
np.min(arr)

-2.2411676156967255

In [25]:
arr.sort(1)
arr.sort(0)
arr

array([[-2.24116762, -1.41551597, -1.38176421, -1.0957435 , -0.11972352,
         0.63971315],
       [-1.47289261, -0.7920735 , -0.37514185, -0.14532864,  0.72588025,
         0.8916625 ],
       [-1.25463262, -0.77818867,  0.25021438,  0.76027132,  1.60772698,
         2.0603444 ]])

In [30]:
max = arr[-1,-1]
max

2.0603443986202983

In [29]:
min = arr[0,0]
min

-2.2411676156967255