## Numpy基础

### 1、ndarray数组基础

**导入**

In [1]:
import numpy as np

**创建数组**

创建数组是进行数组计算的第一步，可以通过numpy库包内的array()函数定义数组实例对象，其参数为Python的序列对象，如果想定义多维数组，则传递多层嵌套的序列。

In [6]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [7]:
print(a)

[1 2 3 4]


In [10]:
b=np.array([[2,3,4],[5,6,7]])
print(b)

[[2 3 4]
 [5 6 7]]


In [13]:
c=np.array([[1,2,3.],[4,5,6]])
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


**数组属性**

   查看行数使用ndim，或者说查看数组第一维是多少（第一维是行，第二维是列）

In [16]:
c.ndim

2

In [17]:
a.ndim

1

查看数组的维数使用shape，返回(n,m),其中n为行数，m为列数。

In [18]:
c.shape

(2, 3)

In [19]:
a.shape

(4,)

查看元素类型使用dtype，比如：numpy.int32,numpy.float64

In [20]:
b.dtype

dtype('int32')

In [21]:
c.dtype

dtype('float64')

### 2、特殊数组

Numpy的特殊数组主要有以下三种：

zeros数组：全零数组，元素全为0.

ones数组：全1数组，元素全为1.

empty数组：空数组，元素全近似为0.

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [99]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [24]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
np.empty((4,3))

array([[1.22705653e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 8.90104238e-307, 3.24791862e-057],
       [1.54754848e-075, 2.17638038e-076, 5.06058065e-038],
       [2.44095326e-052, 8.47274966e+165, 6.70730319e+170]])

### 3、序列数组

arange数组：属于Numpy库，其参数依次为：开始值，结束值，步长。

In [28]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

linspace函数创建等差序列数组，其参数依次为：开始值，结束值，元素数量。

In [33]:
np.linspace(0,100,2)

array([  0., 100.])

In [36]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### 4、数组索引

Numpy数组的每个元素、每行元素、每列元素都可以用索引访问。注意，索引是从0开始的。其操作与列表基本相同。

In [39]:
a=np.array([[1,2,3],[5,6,7]])
a

array([[1, 2, 3],
       [5, 6, 7]])

In [40]:
a[0,1]

2

In [43]:
a[0]

array([1, 2, 3])

In [44]:
a[0,:]

array([1, 2, 3])

In [46]:
a[0,1:3]

array([2, 3])

In [47]:
a[0:2,1]

array([2, 6])

### 5、数组运算

In [48]:
a = np.array([1,2,3])
b = np.array([3,4,5])

1、加法运算

In [49]:
a+b

array([4, 6, 8])

2、减法运算

In [50]:
a-b

array([-2, -2, -2])

3、乘法运算

In [53]:
a*b

array([ 3,  8, 15])

4、乘方运算：a的2次方

In [55]:
a**2

array([1, 4, 9], dtype=int32)

In [56]:
a**3

array([ 1,  8, 27], dtype=int32)

5、除法运算

In [57]:
b/a

array([3.        , 2.        , 1.66666667])

6、判断大小，返回boolean值

In [58]:
a >= 2

array([False,  True,  True])

In [59]:
b <= 4 

array([ True,  True, False])

7、a中最大的元素

In [60]:
max(a)

3

8、a中最小的元素

In [64]:
min(a)

1

In [65]:
a.min()

1

9、a中的和

In [62]:
sum(a)

6

In [66]:
a.sum()

6

### 6、数组拷贝

数组的拷贝分为浅拷贝和深拷贝两种：

浅拷贝通过数组变量的复制完成，浅拷贝只拷贝数组的引用，如果对拷贝对象修改，原数组也将修改。<br>
深拷贝使用数组对象的copy方法完成，在内存中分开存放，改变拷贝数组，原数组不会改变。

In [71]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
b=a
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [77]:
b[1,2]=9
print(b)

[[1. 1. 1.]
 [1. 1. 9.]]


In [78]:
print(a)

[[1. 1. 1.]
 [1. 1. 9.]]


In [80]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [82]:
b=a.copy()
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [85]:
b[1,2]=9
b

array([[1., 1., 1.],
       [1., 1., 9.]])

In [86]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

## 转置

In [90]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [91]:
a.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [93]:
b=np.array([[1,2],[3,4],[5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
b.T

array([[1, 3, 5],
       [2, 4, 6]])

In [95]:
a-b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [96]:
a.T+b

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [97]:
b.T-a

array([[0., 2., 4.],
       [1., 3., 5.]])