## Numpy基础2

### 1、快速的元素级数组函数

In [1]:
import numpy as np

In [5]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
print(np.exp(a))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


### 2、条件逻辑转述为数组运算

**np.where(condition,x,y)**

In [10]:
x = np.array([1,0,3,-2,5,-1])
result = np.where(x>0,x,0)
result

array([1, 0, 3, 0, 5, 0])

In [11]:
x = np.array([1,0,3,-2,5,-1])
result = np.where(x>0,100,0)
result

array([100,   0, 100,   0, 100,   0])

In [14]:
x = np.array([100,74,59,43,61,95])
result = np.where(x>60,'及格','不及格')
result

array(['及格', '及格', '不及格', '不及格', '及格', '及格'], dtype='<U3')

**np.where(condition)**

In [15]:
x = np.array([1,0,3,-2,5,-1])
result = np.where(x>0)
result

(array([0, 2, 4], dtype=int64),)

In [18]:
y = np.array([2,4,1,2,3,0])
result2 = np.where(x<y)
result2

(array([0, 1, 3, 5], dtype=int64),)

### 3、数组基本统计方法

In [21]:
a = np.array([2,4,7,4,5])

In [22]:
np.sum(a)

22

In [23]:
np.mean(a)

4.4

In [24]:
np.max(a)

7

In [25]:
np.min(a)

2

In [27]:
np.std(a)

1.624807680927192

In [28]:
b = [1,2,3,4,5]

In [29]:
np.sum(b)

15

### 4、随机数生成

**numpy.random.normal(loc=0.0,scale=1.0,size=None)**

In [31]:
s1 = np.random.normal(size=(3,3))
s1

array([[-0.43420439, -1.22030059, -0.90146933],
       [ 1.42981594,  0.69290626,  0.39336965],
       [-0.29053339, -1.08218117, -0.0777182 ]])

**numpy.random.randn(d0,d1,...dn)**

In [39]:
s2 = np.random.randn(1,2)
s2

array([[-0.56376657, -2.47495193]])

In [41]:
s2 = np.random.randn(2,1)
s2

array([[-0.54549516],
       [-0.53254362]])

In [52]:
s2 = np.random.randn(1,2,3,4)
s2

array([[[[ 0.09440266, -1.38095529,  0.93299594,  0.0145605 ],
         [-0.74007695, -1.10376297,  1.17318365,  0.61036848],
         [ 0.57953009, -0.32175299,  0.46107949, -0.14139579]],

        [[ 1.13842543, -0.37338509,  0.62804484,  2.9764006 ],
         [ 0.76343472,  1.6867444 ,  0.84152108,  0.71392979],
         [ 0.26078297, -0.92913952,  2.21343568, -0.0918346 ]]]])

In [63]:
sss = np.random.randn(4)
sss

array([ 0.28761502,  0.65315191,  0.88019325, -0.70124522])

**numpy.random.uniform(low,high,size)**

In [47]:
s3 = np.random.uniform(2,19,size=(5,5))
s3

array([[15.18868209,  5.22062111, 18.17618594,  7.61641248,  7.27938193],
       [11.58752501,  5.14791778,  6.12817027,  3.25313407,  2.31454243],
       [10.44478484, 18.92745307, 14.77799126,  7.54391693, 11.39197979],
       [11.31150512, 10.35198379, 11.25195378, 17.65711162,  7.97142158],
       [13.73473957, 14.40215324, 12.77451447, 15.47435222, 10.04774208]])

In [48]:
s4 = np.random.randint(2,19,size=(5,5))
s4

array([[ 5, 13, 16, 17,  7],
       [ 5,  5,  3, 15, 14],
       [13, 17, 10, 17,  4],
       [12, 16,  6, 11,  9],
       [10, 12, 15,  6, 17]])

### 5、数组排序

In [64]:
arr = np.random.uniform(2,19,size=(4,3))
arr

array([[ 4.62857493,  6.65684498, 10.87857725],
       [18.34950892,  8.31948817,  8.16204167],
       [17.04283115,  7.85053726,  8.19774361],
       [ 8.02358724,  6.14462278, 13.5279091 ]])

In [65]:
arr.sort(1)
arr

array([[ 4.62857493,  6.65684498, 10.87857725],
       [ 8.16204167,  8.31948817, 18.34950892],
       [ 7.85053726,  8.19774361, 17.04283115],
       [ 6.14462278,  8.02358724, 13.5279091 ]])

In [66]:
arr.sort(0)
arr

array([[ 4.62857493,  6.65684498, 10.87857725],
       [ 6.14462278,  8.02358724, 13.5279091 ],
       [ 7.85053726,  8.19774361, 17.04283115],
       [ 8.16204167,  8.31948817, 18.34950892]])

### 6、reshape

**numpy.reshape(a,newshape,order='C')**

In [68]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)

[1 2 3 4 5 6 7 8]


In [69]:
np.reshape(a,(2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
d = a.reshape((2,4))
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [74]:
d2 = a.reshape((2,2,2))
d2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [75]:
d.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
d.reshape(-1).shape

(8,)

In [77]:
d.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [78]:
d.reshape(-1,1).shape

(8, 1)

In [79]:
d.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [80]:
d.reshape(-1,2).shape

(4, 2)